### ISSUE TITLE
Does OrbitControl support 120Hz?

### ISSUE THREAD

**Issue by m-kolomoyets** [TiagoCavalcante/r3f-native-orbitcontrols#39] opened 2024-02-23 09:59 UTC
Hello!

interesting if it is possible to set up the component for 120Hz screens, because I have a project with useFrame idle model rotation and few animations on model press with useSpring hooks. And these animations are smooth on 120Hz screens.

But when I rotate or pan the scene, the moves are throttled to 60Hz.

Would be glad for any guide and tip how to customize the controls for 60+Hz screens.

Thanks in advance!

**Comment by TiagoCavalcante** [comment] 2024-02-23 12:44
Hi @m-kolomoyets!

I haven't tested the orbit-controls in 60+Hz screens yet.

Can you send the code with the `useSpring` and the "benchmark" part which you are using to check the refresh rate?

I think this problem may be related to a difference between @react-three/fiber's `invalidate` (used in this lib) and `applyProps` (used in react-spring).

**Comment by TiagoCavalcante** [comment] 2024-04-04 00:17
@m-kolomoyets I have added a branch `stats` to the [example app](https://github.com/TiagoCavalcante/r3f-orbitcontrols-example).

I still haven't been able to test it on 60+Hz screens, but this seems to be [a React Native problem](https://github.com/facebook/react-native/issues/29333).

I'm closing this now, please re-open it if you think the issue is on this library side.

**Closed by TiagoCavalcante** 2024-04-04 00:17 UTC
